dataset_name: navigate
description: 'Date una serie di istruzioni di navigazione, determinare se si tornerà al punto di partenza.'
doc_to_choice: ["Sì","No"]
fewshot_config:
  sampler: first_n
  samples:
  - input_translated: "Se segui queste istruzioni, ritorni al punto di partenza?
      Mantieni sempre la direzione frontale. Fai 2 passi a destra. Fai 9 passi a sinistra. Fai 7 passi a destra.

      Opzioni:

      - Sì

      - No"
    target_translated: 'Sì'
  - input_translated: "Se segui queste istruzioni, ritorni al punto di partenza?
      Gira a sinistra. Girati. Gira a sinistra. Fai 7 passi. Fai 2 passi. Fai 4 passi.
      Fai 8 passi.

      Opzioni:

      - Sì

      - No"
    target_translated: 'No'
  - input_translated: "Se segui queste istruzioni, ritorni al punto di partenza?
      Girati. Fai 1 passo. Fai 6 passi. Girati. Fai 6 passi. Fai 9 passi.
      Fai 1 passo.

      Opzioni:

      - Sì

      - No"
    target_translated: 'No'
include: _fewshot_template_yaml
task: leaderboard_bbh_navigate
