dataset_name: salient_translation_error_detection
description: 'Rileva il tipo di errore nella traduzione inglese di una frase originale tedesca.'
doc_to_choice: ["(A)","(B)","(C)","(D)","(E)","(F)"]
fewshot_config:
  sampler: first_n
  samples:
  - input_translated: "Le seguenti traduzioni dal tedesco all’inglese contengono un particolare errore.
      Tale errore sarà di uno dei seguenti tipi: Entità nominate: Un’entità (nomi, luoghi, località, ecc.) viene cambiata in un’altra entità. Valori numerici: Valori numerici (ordinali o cardinali), date e/o unità vengono modificati. Modificatori o aggettivi: I modificatori e gli aggettivi relativi a un sostantivo vengono cambiati. Negazione o contrari: Viene introdotta o rimossa una negazione oppure vengono cambiati comparativi con i loro contrari. Fatti: Vengono introdotti errori fattuali banali non appartenenti alle categorie precedenti. Contenuto omesso (Dropped Content): Una parte significativa della frase viene omessa nella traduzione.
      Identifica l’errore.  
      
      Fonte: In der Liste der Baudenkmale in Lenzen (Elbe) sind alle Baudenkmale der brandenburgischen
      Stadt Lenzen (Elbe) und ihrer Ortsteile aufgelistet.

      Traduzione: In the list of architectural monuments in Lenzen all architectural
      monuments of the Brandenburg city of Lenzen and its districts are listed.

      La traduzione contiene un errore relativo a:

      Opzioni:
      (A) Modificatori o aggettivi
      (B) Valori numerici
      (C) Negazione o contrari
      (D) Entità nominate
      (E) Contenuto omesso
      (F) Fatti"
    target_translated: (D)
  - input_translated: "Le seguenti traduzioni dal tedesco all’inglese contengono un particolare errore.
      Tale errore sarà di uno dei seguenti tipi: Entità nominate: Un’entità (nomi, luoghi, località, ecc.) viene cambiata in un’altra entità. Valori numerici: Valori numerici (ordinali o cardinali), date e/o unità vengono modificati. Modificatori o aggettivi: I modificatori e gli aggettivi relativi a un sostantivo vengono cambiati. Negazione o contrari: Viene introdotta o rimossa una negazione oppure vengono cambiati comparativi con i loro contrari. Fatti: Vengono introdotti errori fattuali banali non appartenenti alle categorie precedenti. Contenuto omesso (Dropped Content): Una parte significativa della frase viene omessa nella traduzione.
      Identifica l’errore.  
      
      Fonte: Auf dieser Seite sind die Baudenkmäler der oberbayerischen Großen Kreisstadt Landsberg am Lech zusammengestellt.

      Traduzione: On this page are compiled the architectural monuments of the town of Landsberg am Lech.

      La traduzione contiene un errore relativo a:

      Opzioni:
      (A) Modificatori o aggettivi
      (B) Valori numerici
      (C) Negazione o contrari
      (D) Entità nominate
      (E) Contenuto omesso
      (F) Fatti"
    target_translated: (E)
  - input_translated: "Le seguenti traduzioni dal tedesco all’inglese contengono un particolare errore.
      Tale errore sarà di uno dei seguenti tipi: Entità nominate: Un’entità (nomi, luoghi, località, ecc.) viene cambiata in un’altra entità. Valori numerici: Valori numerici (ordinali o cardinali), date e/o unità vengono modificati. Modificatori o aggettivi: I modificatori e gli aggettivi relativi a un sostantivo vengono cambiati. Negazione o contrari: Viene introdotta o rimossa una negazione oppure vengono cambiati comparativi con i loro contrari. Fatti: Vengono introdotti errori fattuali banali non appartenenti alle categorie precedenti. Contenuto omesso (Dropped Content): Una parte significativa della frase viene omessa nella traduzione.
      Identifica l’errore.  
      
      Fonte: Łeba ist eine Kleinstadt und ein Badeort im Powiat Lęborski der polnischen Woiwodschaft Pommern.

      Traduzione: Eba is not a small town and seaside resort in the Powiat Léborski county of the Pomeranian Voivodeship of Poland.

      La traduzione contiene un errore relativo a:

      Opzioni:
      (A) Modificatori o aggettivi
      (B) Valori numerici
      (C) Negazione o contrari
      (D) Entità nominate
      (E) Contenuto omesso
      (F) Fatti"
    target_translated: (C)
include: _fewshot_template_yaml
task: leaderboard_bbh_salient_translation_error_detection
