include: _pretens_yaml

task: itabench_pretens_p2

doc_to_text: "Devi capire se una frase data ha semanticamente senso\n{{text}}\nDomanda: La frase precedente ha senso?"
doc_to_target: label
doc_to_choice: ["no", "s√¨"]