group: itabench_leaderboard_musr_it
task:
  - leaderboard_musr_murder_mysteries_it
  - leaderboard_musr_object_placements_it
  - leaderboard_musr_team_allocation_it
aggregate_metric_list:
  - metric: acc_norm
    aggregation: mean
    weight_by_size: true
