group: itabench_leaderboard_it
task:
  - itabench_leaderboard_mmlu_pro_it
  - itabench_leaderboard_bbh_it
  - itabench_leaderboard_gpqa_it
  - itabench_leaderboard_math_hard_it
  - itabench_leaderboard_ifeval_it
  - itabench_leaderboard_musr_it
aggregate_metric_list:
  - metric: acc
    aggregation: mean
    weight_by_size: true 
  - metric: acc_norm
    aggregation: mean
    weight_by_size: true 
  - metric: exact_match
    aggregation: mean
    weight_by_size: true 
  - metric: inst_level_loose_acc
    aggregation: mean
    weight_by_size: true 
  - metric: inst_level_strict_acc
    aggregation: mean
    weight_by_size: true 
  - metric: prompt_level_loose_acc
    aggregation: mean
    weight_by_size: true 
  - metric: prompt_level_strict_acc
    aggregation: mean
    weight_by_size: true 
metadata:
  version: 1.0
