include: _ami_synth_yaml
task: itabench_ami_synth_p1
dataset_name: Synth
doc_to_text: "Quale Ã¨ il livello di misoginia nel seguente tweet '{{text}}'?"
doc_to_target: label
doc_to_choice: ["Neutro", "Misogino"]