include: _ami_synth_yaml
task: itabench_ami_synth_p3

doc_to_text: "Il seguente tweet contiene caratteristiche misogine: '{{text}}'?\nA. no\nB. s√¨\nRisposta:"
doc_to_target: label
doc_to_choice: ["A", "B"]