dataset_name: logical_deduction_five_objects
description: "Risolvi un compito di deduzione logica che richiede di dedurre l'ordine di una sequenza di oggetti."
doc_to_choice: ["(A)","(B)","(C)","(D)","(E)"]
fewshot_config:
  sampler: first_n
  samples:
  - input_translated: "I seguenti paragrafi descrivono ciascuno un insieme di tre oggetti disposti in un ordine fisso. Le affermazioni sono logicamente coerenti all’interno di ogni paragrafo.
      In un torneo di golf c’erano tre golfisti: Amy, Eli ed Eve. Eve è arrivata davanti ad Amy. Eli è arrivato dietro ad Amy.

      Opzioni:

      (A) Amy è arrivata ultima
      (B) Eli è arrivato ultimo
      (C) Eve è arrivata ultima"
    target_translated: (B)
  - input_translated: "I seguenti paragrafi descrivono ciascuno un insieme di tre oggetti disposti in un ordine fisso. Le affermazioni sono logicamente coerenti all’interno di ogni paragrafo.
      Su uno scaffale ci sono tre libri: un libro bianco, un libro verde e un libro arancione. Il libro verde è a destra del libro bianco. Il libro arancione è quello più a destra.

      Opzioni:

      (A) Il libro bianco è quello più a sinistra
      (B) Il libro verde è quello più a sinistra
      (C) Il libro arancione è quello più a sinistra"
    target_translated: (A)
  - input_translated: "I seguenti paragrafi descrivono ciascuno un insieme di tre oggetti disposti in un ordine fisso. Le affermazioni sono logicamente coerenti all’interno di ogni paragrafo.
      Su uno scaffale ci sono tre libri: un libro rosso, un libro grigio e un libro bianco. Il libro bianco è alla sinistra del libro grigio. Il libro rosso è il secondo da sinistra.

      Opzioni:

      (A) Il libro rosso è quello più a sinistra
      (B) Il libro grigio è quello più a sinistra
      (C) Il libro bianco è quello più a sinistra"
    target_translated: (C)
include: _fewshot_template_yaml
task: leaderboard_bbh_logical_deduction_five_objects
