dataset_name: object_counting
description: "Domande che implicano l'enumerazione di oggetti e la richiesta al modello di contarli."
doc_to_choice: ["0","1","2","3","4","5","6","7","8","9","10", "11", "12", "13", "14", "15", "16", "17", "18"]
fewshot_config:
  sampler: first_n
  samples:
  - input_translated: Ho una mora, un clarinetto, una nettarina, una prugna, una fragola, una banana,
      un flauto, un’arancia e un violino. Quanti frutti ho?
    target_translated: '6'
  - input_translated: Ho un’arancia, un lampone, due pesche, una mora, una mela, un acino d’uva,
      una nettarina e tre prugne. Quanti frutti ho?
    target_translated: '11'
  - input_translated: Ho un cespo di lattuga, una testa di broccoli, una cipolla, un gambo di sedano,
      due carote, un aglio e una patata dolce. Quante verdure ho?
    target_translated: '8'
include: _fewshot_template_yaml
task: leaderboard_bbh_object_counting
